remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 

title: [A Geekier Blog]
description: [My blog about technology, programming, guides I wrote, and other geeky stuff.]

show_downloads: [false]
