remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

website: https://mmartial.github.io/
basewebsite: /geekier-blog
permalink: date

show_downloads: [false]
title: [A_Geekier_Blog]
description: [Tech wrteups]

